site_name: example-uvcookiecutter
repo_url: https://github.com/tleonhardt/example-uvcookiecutter
site_url: https://tleonhardt.github.io/example-uvcookiecutter
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Todd Leonhardt
edit_uri: edit/main/docs/
repo_name: tleonhardt/example-uvcookiecutter
copyright: Maintained by <a href="https://tleonhardt.com">tleonhardt</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [example_uvcookiecutter]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tleonhardt/example-uvcookiecutter
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/example-uvcookiecutter

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
